//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApps.Helpers {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResourcesFR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResourcesFR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MobileApps.Helpers.AppResourcesFR", typeof(AppResourcesFR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CampusPageTitle {
            get {
                return ResourceManager.GetString("CampusPageTitle", resourceCulture);
            }
        }
        
        public static string CitizenshipPageTitle {
            get {
                return ResourceManager.GetString("CitizenshipPageTitle", resourceCulture);
            }
        }
        
        public static string EmailAgreeTitle {
            get {
                return ResourceManager.GetString("EmailAgreeTitle", resourceCulture);
            }
        }
        
        public static string EmailEntryTitle {
            get {
                return ResourceManager.GetString("EmailEntryTitle", resourceCulture);
            }
        }
        
        public static string EmailMainTitle {
            get {
                return ResourceManager.GetString("EmailMainTitle", resourceCulture);
            }
        }
        
        public static string NamePageFirstNameTitle {
            get {
                return ResourceManager.GetString("NamePageFirstNameTitle", resourceCulture);
            }
        }
        
        public static string NamePageLastNameTitle {
            get {
                return ResourceManager.GetString("NamePageLastNameTitle", resourceCulture);
            }
        }
        
        public static string NamePageMainTitle {
            get {
                return ResourceManager.GetString("NamePageMainTitle", resourceCulture);
            }
        }
        
        public static string ObjectivePageTitle {
            get {
                return ResourceManager.GetString("ObjectivePageTitle", resourceCulture);
            }
        }
        
        public static string ProgramsPageTitle {
            get {
                return ResourceManager.GetString("ProgramsPageTitle", resourceCulture);
            }
        }
        
        public static string ProgramsCategoryPrompt {
            get {
                return ResourceManager.GetString("ProgramsCategoryPrompt", resourceCulture);
            }
        }
        
        public static string ProgramsCategoryPlaceholder {
            get {
                return ResourceManager.GetString("ProgramsCategoryPlaceholder", resourceCulture);
            }
        }
        
        public static string TelephonePageHomePhoneTitle {
            get {
                return ResourceManager.GetString("TelephonePageHomePhoneTitle", resourceCulture);
            }
        }
        
        public static string TelephonePageMainTitle {
            get {
                return ResourceManager.GetString("TelephonePageMainTitle", resourceCulture);
            }
        }
        
        public static string TelephonePageMobilePhoneTitle {
            get {
                return ResourceManager.GetString("TelephonePageMobilePhoneTitle", resourceCulture);
            }
        }
        
        public static string ThankYouPageSubTitleKiosk {
            get {
                return ResourceManager.GetString("ThankYouPageSubTitleKiosk", resourceCulture);
            }
        }
        
        public static string ThankYouPageSubTitleEvent {
            get {
                return ResourceManager.GetString("ThankYouPageSubTitleEvent", resourceCulture);
            }
        }
        
        public static string ThankYouPageTitle {
            get {
                return ResourceManager.GetString("ThankYouPageTitle", resourceCulture);
            }
        }
        
        public static string CampusPageError1 {
            get {
                return ResourceManager.GetString("CampusPageError1", resourceCulture);
            }
        }
        
        public static string CampusPageError2 {
            get {
                return ResourceManager.GetString("CampusPageError2", resourceCulture);
            }
        }
        
        public static string CitizenshipPageError1 {
            get {
                return ResourceManager.GetString("CitizenshipPageError1", resourceCulture);
            }
        }
        
        public static string CitizenshipPageError2 {
            get {
                return ResourceManager.GetString("CitizenshipPageError2", resourceCulture);
            }
        }
        
        public static string CountriesSearchPlaceholder {
            get {
                return ResourceManager.GetString("CountriesSearchPlaceholder", resourceCulture);
            }
        }
        
        public static string EmailPageError1 {
            get {
                return ResourceManager.GetString("EmailPageError1", resourceCulture);
            }
        }
        
        public static string EmailPageError2 {
            get {
                return ResourceManager.GetString("EmailPageError2", resourceCulture);
            }
        }
        
        public static string NamePageError1 {
            get {
                return ResourceManager.GetString("NamePageError1", resourceCulture);
            }
        }
        
        public static string NamePageError2 {
            get {
                return ResourceManager.GetString("NamePageError2", resourceCulture);
            }
        }
        
        public static string ObjectivePageError1 {
            get {
                return ResourceManager.GetString("ObjectivePageError1", resourceCulture);
            }
        }
        
        public static string ProgramsPageError1 {
            get {
                return ResourceManager.GetString("ProgramsPageError1", resourceCulture);
            }
        }
        
        public static string ProgramsPageError2 {
            get {
                return ResourceManager.GetString("ProgramsPageError2", resourceCulture);
            }
        }
        
        public static string TelephonePageError1 {
            get {
                return ResourceManager.GetString("TelephonePageError1", resourceCulture);
            }
        }
        
        public static string TelephonePageError2 {
            get {
                return ResourceManager.GetString("TelephonePageError2", resourceCulture);
            }
        }
    }
}
