using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MobileApps.Core.Helpers
{
    public class CountryGenerator
    {
        IList<string> results = new List<string>();
        public IList<string> countries()
        {
            results.Add("Afghanistan");
            results.Add("Albania");
            results.Add("Algeria");
            results.Add("American Virgin Islands");
            results.Add("Andorra");
            results.Add("Angola");
            results.Add("Anguilla");
            results.Add("Antigua and Barbuda");
            results.Add("Argentina");
            results.Add("Armenia");
            results.Add("Aruba");
            results.Add("Australia");
            results.Add("Austria");
            results.Add("Azerbaijan");
            results.Add("Bahamas");
            results.Add("Bahrain");
            results.Add("Bangladesh");
            results.Add("Barbados");
            results.Add("Belarus");
            results.Add("Belgium");
            results.Add("Belize");
            results.Add("Benin");
            results.Add("Bermuda");
            results.Add("Bhutan");
            results.Add("Bolivia");
            results.Add("Bonaire, Sint Eustatius and Saba");
            results.Add("Bosnia and Herzegovina");
            results.Add("Botswana");
            results.Add("Brazil");
            results.Add("British Virgin Islands");
            results.Add("Brunei");
            results.Add("Bulgaria");
            results.Add("Burkina-Faso");
            results.Add("Burundi");
            results.Add("Cambodia");
            results.Add("Cameroun");
            results.Add("Canada");
            results.Add("Cape Verde");
            results.Add("Cayman Islands");
            results.Add("Central African Republic");
            results.Add("Chad");
            results.Add("Chile");
            results.Add("China");
            results.Add("Christmas Island");
            results.Add("Cocos (Keeling) Islands");
            results.Add("Colombia");
            results.Add("Comoros");
            results.Add("Congo, Democratic Republic of");
            results.Add("Congo, Republic of");
            results.Add("Cook Islands");
            results.Add("Costa Rica");
            results.Add("Country not specified");
            results.Add("Croatia");
            results.Add("Cuba");
            results.Add("Curacao");
            results.Add("Cyprus");
            results.Add("Czech Republic");
            results.Add("Democratic People's Republic of Korea");
            results.Add("Denmark");
            results.Add("Djibouti");
            results.Add("Dominica");
            results.Add("Dominican Republic");
            results.Add("Ecuador");
            results.Add("Egypt");
            results.Add("El Salvador");
            results.Add("Equatorial Guinea");
            results.Add("Eritrea");
            results.Add("Estonia");
            results.Add("Ethiopia");
            results.Add("Falkland Islands");
            results.Add("Faroe Islands");
            results.Add("Fidji");
            results.Add("Finland");
            results.Add("France");
            results.Add("French Guiana");
            results.Add("French Polynesia");
            results.Add("Gabon");
            results.Add("Gambia");
            results.Add("Georgia");
            results.Add("Germany");
            results.Add("Ghana");
            results.Add("Gibraltar");
            results.Add("Greece");
            results.Add("Greenland");
            results.Add("Grenada");
            results.Add("Guadeloupe");
            results.Add("Guam");
            results.Add("Guatemala");
            results.Add("Guernesey");
            results.Add("Guinea");
            results.Add("Guinea-Bissau");
            results.Add("Guyana");
            results.Add("Haiti");
            results.Add("Honduras");
            results.Add("Hong Kong");
            results.Add("Hungary");
            results.Add("Iceland");
            results.Add("India");
            results.Add("Indonesia");
            results.Add("Iran");
            results.Add("Iraq");
            results.Add("Ireland");
            results.Add("Isle of Man");
            results.Add("Israel");
            results.Add("Italy");
            results.Add("Ivory Coast");
            results.Add("Jamaica");
            results.Add("Japan");
            results.Add("Jersey");
            results.Add("Jordan");
            results.Add("Kazakhstan");
            results.Add("Kenya");
            results.Add("Kiribati");
            results.Add("Kosovo");
            results.Add("Kuwait");
            results.Add("Kyrgyzstan");
            results.Add("Laos");
            results.Add("Latvia");
            results.Add("Lebanon");
            results.Add("Lesotho");
            results.Add("Liberia");
            results.Add("Libya");
            results.Add("Liechtenstein");
            results.Add("Lithuania");
            results.Add("Luxembourg");
            results.Add("Macao");
            results.Add("Macedonia");
            results.Add("Madagascar");
            results.Add("Malawi");
            results.Add("Malaysia");
            results.Add("Maldives");
            results.Add("Mali");
            results.Add("Malta");
            results.Add("Marshall Islands");
            results.Add("Martinique");
            results.Add("Mauritania");
            results.Add("Mauritius");
            results.Add("Mayotte Islands");
            results.Add("Mexico");
            results.Add("Micronesia");
            results.Add("Moldavia");
            results.Add("Monaco");
            results.Add("Mongolia");
            results.Add("Montenegro");
            results.Add("Montserrat");
            results.Add("Morocco");
            results.Add("Mozambique");
            results.Add("Myanmar");
            results.Add("Namibia");
            results.Add("Nauru");
            results.Add("Nepal");
            results.Add("Netherlands");
            results.Add("New Caledonia");
            results.Add("New Zealand");
            results.Add("Nicaragua");
            results.Add("Niger");
            results.Add("Nigeria");
            results.Add("Niue");
            results.Add("Norfolk Islands");
            results.Add("Northern Mariana Islands");
            results.Add("Norway");
            results.Add("Oman");
            results.Add("Other");
            results.Add("Pakistan");
            results.Add("Palau");
            results.Add("Panama");
            results.Add("Papua New Guinea");
            results.Add("Paraguay");
            results.Add("Peru");
            results.Add("Philippines");
            results.Add("Pitcairn");
            results.Add("Poland");
            results.Add("Portugal");
            results.Add("Puerto Rico");
            results.Add("Qatar");
            results.Add("Republic of Korea");
            results.Add("Republic of Moldova");
            results.Add("Réunion");
            results.Add("Romania");
            results.Add("Russia");
            results.Add("Rwanda");
            results.Add("Saint Barthélemy");
            results.Add("Saint Helena");
            results.Add("Saint Kitts and Nevis");
            results.Add("Saint Martin (French Part)");
            results.Add("Saint-Lucie");
            results.Add("Saint-Pierre and Miquelon");
            results.Add("Saint-Vincent and Grenadines");
            results.Add("Samoa");
            results.Add("San Marino");
            results.Add("Sao Tome and Principe");
            results.Add("Saudi Arabia");
            results.Add("Senegal");
            results.Add("Serbia");
            results.Add("Seychelles");
            results.Add("Sierra Leones");
            results.Add("Singapore");
            results.Add("Sint Maarten (Dutch Part)");
            results.Add("Slovakia");
            results.Add("Slovenia");
            results.Add("Solomon Islands");
            results.Add("Somalia");
            results.Add("South Africa");
            results.Add("South Georgia and the South Sandwich Islands");
            results.Add("South Sudan");
            results.Add("South Yemen");
            results.Add("Spain");
            results.Add("Sri Lanka");
            results.Add("State of Palestinian");
            results.Add("Stateless person");
            results.Add("Sudan");
            results.Add("Surinam");
            results.Add("Swaziland");
            results.Add("Sweden");
            results.Add("Switzerland");
            results.Add("Syria");
            results.Add("Taiwan");
            results.Add("Tajikistan");
            results.Add("Tanzania");
            results.Add("Thailand");
            results.Add("Timor-Leste");
            results.Add("Togo");
            results.Add("Tokelau");
            results.Add("Tonga");
            results.Add("Trinidad and Tobago");
            results.Add("Tunisia");
            results.Add("Turkey");
            results.Add("Turkmenistan");
            results.Add("Tuvalu");
            results.Add("Uganda");
            results.Add("Ukraine");
            results.Add("United Arab Emirates");
            results.Add("United Kingdom");
            results.Add("United States");
            results.Add("Unknown country");
            results.Add("Uruguay");
            results.Add("Uzbekistan");
            results.Add("Vanuatu");
            results.Add("Vatican");
            results.Add("Venezuela");
            results.Add("Vietnam");
            results.Add("Wallis and Futuna Islands");
            results.Add("Western Sahara");
            results.Add("Yemen");
            results.Add("Zambia");
            results.Add("Zimbabwe");

            return results;
        }
    }
}
