//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApps.Core.Helpers.ValidationMessages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessagesFR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessagesFR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileApps.Core.Helpers.ValidationMessages.ValidationMessagesFR", typeof(ValidationMessagesFR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * S&apos;il vous plaît sélectionner un campus.
        /// </summary>
        internal static string CampusPageError1 {
            get {
                return ResourceManager.GetString("CampusPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * No Aucun campus trouve, Mettez a jour la base de donnees.
        /// </summary>
        internal static string CampusPageError2 {
            get {
                return ResourceManager.GetString("CampusPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * S&apos;il vous plaît sélectionner un citoyenneté.
        /// </summary>
        internal static string CitizenshipPageError1 {
            get {
                return ResourceManager.GetString("CitizenshipPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Aucun pays trouve, Mettez a jour la base de donnees.
        /// </summary>
        internal static string CitizenshipPageError2 {
            get {
                return ResourceManager.GetString("CitizenshipPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Veuillez entrer une adresse courriel.
        /// </summary>
        internal static string EmailPageError1 {
            get {
                return ResourceManager.GetString("EmailPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Veuillez entrer une adresse courriel valide.
        /// </summary>
        internal static string EmailPageError2 {
            get {
                return ResourceManager.GetString("EmailPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * S&apos;il vous plaît remplir les deux Nom et Prénom.
        /// </summary>
        internal static string NamePageError1 {
            get {
                return ResourceManager.GetString("NamePageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * S&apos;il vous plaît entrez alphabétique caractères seulement.
        /// </summary>
        internal static string NamePageError2 {
            get {
                return ResourceManager.GetString("NamePageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * S&apos;il vous plaît sélectionner un objectif.
        /// </summary>
        internal static string ObjectivePageError1 {
            get {
                return ResourceManager.GetString("ObjectivePageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * S&apos;il vous plaît sélectionner une programme.
        /// </summary>
        internal static string ProgramsPageError1 {
            get {
                return ResourceManager.GetString("ProgramsPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Aucun programmes trouve, Mettez a jour la base de donnees.
        /// </summary>
        internal static string ProgramsPageError2 {
            get {
                return ResourceManager.GetString("ProgramsPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * S&apos;il vous plait entrez au moins un numero de telephone.
        /// </summary>
        internal static string TelephonePageError1 {
            get {
                return ResourceManager.GetString("TelephonePageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * S&apos;il vous plait entrer un numero de telephone valide..
        /// </summary>
        internal static string TelephonePageError2 {
            get {
                return ResourceManager.GetString("TelephonePageError2", resourceCulture);
            }
        }
    }
}
