//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApps.Core.Helpers.ValidationMessages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessagesCA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessagesCA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileApps.Core.Helpers.ValidationMessages.ValidationMessagesCA", typeof(ValidationMessagesCA).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Si us plau, selecciona un campus.
        /// </summary>
        internal static string CampusPageError1 {
            get {
                return ResourceManager.GetString("CampusPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * No s’han trobat aquests Campus, actualitzi la Base de Dades.
        /// </summary>
        internal static string CampusPageError2 {
            get {
                return ResourceManager.GetString("CampusPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Si us plau, selecciona la teva nacionalitat.
        /// </summary>
        internal static string CitizenshipPageError1 {
            get {
                return ResourceManager.GetString("CitizenshipPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * No s’han trobat aquests Països, actualitzi la Base de Dades.
        /// </summary>
        internal static string CitizenshipPageError2 {
            get {
                return ResourceManager.GetString("CitizenshipPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El correu electrònic no pot anar buit.
        /// </summary>
        internal static string EmailPageError1 {
            get {
                return ResourceManager.GetString("EmailPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Format d’adreça de correu electrònic no vàlid.
        /// </summary>
        internal static string EmailPageError2 {
            get {
                return ResourceManager.GetString("EmailPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Si us plau, indica el teu nom i cognom.
        /// </summary>
        internal static string NamePageError1 {
            get {
                return ResourceManager.GetString("NamePageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Si us plau, introdueix només caràcters alfabètics.
        /// </summary>
        internal static string NamePageError2 {
            get {
                return ResourceManager.GetString("NamePageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Si us plau, selecciona el teu objectiu.
        /// </summary>
        internal static string ObjectivePageError1 {
            get {
                return ResourceManager.GetString("ObjectivePageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Si us plau, selecciona un programa.
        /// </summary>
        internal static string ProgramsPageError1 {
            get {
                return ResourceManager.GetString("ProgramsPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * No se han encontrado estos Programas, actualice la Base de Datos..
        /// </summary>
        internal static string ProgramsPageError2 {
            get {
                return ResourceManager.GetString("ProgramsPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Introduir, com a mínim, un número de telèfon.
        /// </summary>
        internal static string TelephonePageError1 {
            get {
                return ResourceManager.GetString("TelephonePageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Si us plau, introduir un número de telèfon vàlid.
        /// </summary>
        internal static string TelephonePageError2 {
            get {
                return ResourceManager.GetString("TelephonePageError2", resourceCulture);
            }
        }
    }
}
