//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApps.Core.Helpers.ValidationMessages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessagesES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessagesES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileApps.Core.Helpers.ValidationMessages.ValidationMessagesES", typeof(ValidationMessagesES).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor seleccione un campus.
        /// </summary>
        internal static string CampusPageError1 {
            get {
                return ResourceManager.GetString("CampusPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * No se han encontrado estos Campus, actualice la Base de Datos.
        /// </summary>
        internal static string CampusPageError2 {
            get {
                return ResourceManager.GetString("CampusPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor seleccione su ciudadanía.
        /// </summary>
        internal static string CitizenshipPageError1 {
            get {
                return ResourceManager.GetString("CitizenshipPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * No se han encontrado estos Países, actualice la Base de Datos.
        /// </summary>
        internal static string CitizenshipPageError2 {
            get {
                return ResourceManager.GetString("CitizenshipPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor ingrese una cuenta de correo válido.
        /// </summary>
        internal static string EmailPageError1 {
            get {
                return ResourceManager.GetString("EmailPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor ingrese una cuenta.
        /// </summary>
        internal static string EmailPageError2 {
            get {
                return ResourceManager.GetString("EmailPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor llene su nombre y su apellido.
        /// </summary>
        internal static string NamePageError1 {
            get {
                return ResourceManager.GetString("NamePageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor solo entre caracteres alfabéticos.
        /// </summary>
        internal static string NamePageError2 {
            get {
                return ResourceManager.GetString("NamePageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor seleccione su objetivo.
        /// </summary>
        internal static string ObjectivePageError1 {
            get {
                return ResourceManager.GetString("ObjectivePageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor seleccione un programa.
        /// </summary>
        internal static string ProgramsPageError1 {
            get {
                return ResourceManager.GetString("ProgramsPageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * No se han encontrado estos Programas, actualice la Base de Datos..
        /// </summary>
        internal static string ProgramsPageError2 {
            get {
                return ResourceManager.GetString("ProgramsPageError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Introducir, como mínimo, un número de teléfono.
        /// </summary>
        internal static string TelephonePageError1 {
            get {
                return ResourceManager.GetString("TelephonePageError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor, introducir un número de teléfono válido.
        /// </summary>
        internal static string TelephonePageError2 {
            get {
                return ResourceManager.GetString("TelephonePageError2", resourceCulture);
            }
        }
    }
}
